In [1]:
import pandas as pd
import numpy as np

In [2]:
analysis = pd.read_excel("../data/raw/analysis.xlsx")
balancesheet = pd.read_excel("../data/raw/balancesheet.xlsx")
cashflow = pd.read_excel("../data/raw/cashflow.xlsx")
companies = pd.read_excel("../data/raw/companies.xlsx")
documents = pd.read_excel("../data/raw/documents.xlsx")
profitandloss = pd.read_excel("../data/raw/profitandloss.xlsx")
prosandcons = pd.read_excel("../data/raw/prosandcons.xlsx")

In [5]:
#Dataset Overview
for name, df in datasets.items():

    print("\n")
    print("="*50)
    print(name.upper())
    print("="*50)

    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

==================================================
ANALYSIS
==================================================
Rows: 21
Columns: 6


==================================================
BALANCESHEET
==================================================
Rows: 1313
Columns: 13


==================================================
CASHFLOW
==================================================
Rows: 1188
Columns: 7


==================================================
COMPANIES
==================================================
Rows: 93
Columns: 12


==================================================
DOCUMENTS
==================================================
Rows: 1586
Columns: 4


==================================================
PROFITANDLOSS
==================================================
Rows: 1277
Columns: 15


==================================================
PROSANDCONS
==================================================
Rows: 17
Columns: 4

In [6]:
#Column Names
for name, df in datasets.items():

    print("\n")
    print("="*50)
    print(name.upper())
    print("="*50)

    print(df.columns.tolist())

==================================================
ANALYSIS
==================================================
['Bluestock Fintech — Nifty 100  |  Analysis  |  20 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']


==================================================
BALANCESHEET
==================================================
['Bluestock Fintech — Nifty 100  |  Balance Sheet  |  1,312 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']


==================================================
CASHFLOW
==================================================
['Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6']


==================================================
COMPANIES
==================================================
['Mkt Fintech — Nifty 100  |  Companies  |  92 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11']


==================================================
DOCUMENTS
==================================================
['Bluestock Fintech — Nifty 100  |  Documents  |  1,585 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']


==================================================
PROFITANDLOSS
==================================================
['Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']


==================================================
PROSANDCONS
==================================================
['Bluestock Fintech — Nifty 100  |  Pros & Cons  |  16 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

In [7]:
#First 5 Rows
for name, df in datasets.items():

    print("\n")
    print("="*50)
    print(name.upper())
    print("="*50)

    display(df.head())

==================================================
ANALYSIS
==================================================

,Bluestock Fintech — Nifty 100 | Analysis | 20 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
1,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
2,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
3,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
4,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%

==================================================
BALANCESHEET
==================================================

,"Bluestock Fintech — Nifty 100 | Balance Sheet | 1,312 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
1,136,ABB,Dec 2012,21,626,0,260,907,109,1,0,798,907
2,137,ABB,Mar 2014,21,767,0,351,1139,98,1,0,1040,1139
3,138,ABB,Mar 2015,21,916,0,436,1374,96,4,0,1274,1374
4,139,ABB,Mar 2016,21,1174,0,421,1616,108,3,0,1505,1616

==================================================
CASHFLOW
==================================================

,"Bluestock Fintech — Nifty 100 | Cash Flow | 1,187 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
1,37,TCS,Mar-13,11615,-6038,-5729,-152
2,38,TCS,Mar-14,14751,-9452,-5673,-374
3,39,TCS,Mar-15,19369,-1807,-17168,394
4,40,TCS,Mar-16,19109,-5010,-9666,4433

==================================================
COMPANIES
==================================================

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

==================================================
DOCUMENTS
==================================================

,"Bluestock Fintech — Nifty 100 | Documents | 1,585 records",Unnamed: 1,Unnamed: 2,Unnamed: 3
0,id,company_id,Year,Annual_Report
1,1,ABB,2024,https://www.bseindia.com/xml-data/corpfiling/A...
2,2,ABB,2023,https://www.bseindia.com/xml-data/corpfiling/A...
3,3,ABB,2022,https://www.bseindia.com/bseplus/AnnualReport/...
4,4,ABB,2021,https://www.bseindia.com/bseplus/AnnualReport/...

==================================================
PROFITANDLOSS
==================================================

,"Bluestock Fintech — Nifty 100 | Profit & Loss | 1,276 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
2,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
3,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
4,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29

==================================================
PROSANDCONS
==================================================

,Bluestock Fintech — Nifty 100 | Pros & Cons | 16 records,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,id,company_id,pros,cons
1,1,HDFCBANK,Company is expected to give good quarter,Stock is trading at 2.76 times its book value
2,2,HDFCBANK,Company has delivered good profit growth of 23...,Company has low interest coverage ratio.
3,3,HDFCBANK,Company has been maintaining a healthy dividen...,"Contingent liabilities of Rs.24,09,821 Cr."
4,4,HDFCBANK,Company's median sales growth is 16.4% of last...,"Earnings include an other income of Rs.1,55,87..."

In [8]:
#Missing Values
for name, df in datasets.items():

    print("\n")
    print("="*50)
    print(name.upper())
    print("="*50)

    print(
        "Missing Values:",
        df.isnull().sum().sum()
    )

==================================================
ANALYSIS
==================================================
Missing Values: 0


==================================================
BALANCESHEET
==================================================
Missing Values: 0


==================================================
CASHFLOW
==================================================
Missing Values: 8


==================================================
COMPANIES
==================================================
Missing Values: 9


==================================================
DOCUMENTS
==================================================
Missing Values: 52


==================================================
PROFITANDLOSS
==================================================
Missing Values: 231


==================================================
PROSANDCONS
==================================================
Missing Values: 6

In [9]:
#Duplicate Rows
for name, df in datasets.items():

    print(
        name,
        "Duplicates:",
        df.duplicated().sum()
    )

analysis Duplicates: 0
balancesheet Duplicates: 0
cashflow Duplicates: 0
companies Duplicates: 0
documents Duplicates: 0
profitandloss Duplicates: 0
prosandcons Duplicates: 0

In [10]:
#Complete Summary Table
summary = []

for name, df in datasets.items():

    summary.append([
        name,
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ])

summary_df = pd.DataFrame(
    summary,
    columns=[
        "Table",
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicates"
    ]
)

summary_df

           Table  Rows  Columns  Missing Values  Duplicates
0       analysis    21        6               0           0
1   balancesheet  1313       13               0           0
2       cashflow  1188        7               8           0
3      companies    93       12               9           0
4      documents  1586        4              52           0
5  profitandloss  1277       15             231           0
6    prosandcons    17        4               6           0

In [11]:
#Save Data Understanding Report
summary_df.to_excel(
    "../reports/data_summary.xlsx",
    index=False
)

print("Data summary saved")

Data summary saved

In [12]:
#Detect Header Problems
for name, df in datasets.items():

    print("\n")
    print(name.upper())

    print(df.iloc[0].tolist())

ANALYSIS
['id', 'company_id', 'compounded_sales_growth', 'compounded_profit_growth', 'stock_price_cagr', 'roe']


BALANCESHEET
['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']


CASHFLOW
['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']


COMPANIES
['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']


DOCUMENTS
['id', 'company_id', 'Year', 'Annual_Report']


PROFITANDLOSS
['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']


PROSANDCONS
['id', 'company_id', 'pros', 'cons']

In [13]:
#Create Data Issues Report
issues = []

for name, df in datasets.items():

    issues.append([
        name,
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ])

issues_df = pd.DataFrame(
    issues,
    columns=[
        "Table",
        "Missing Values",
        "Duplicates"
    ]
)

issues_df

           Table  Missing Values  Duplicates
0       analysis               0           0
1   balancesheet               0           0
2       cashflow               8           0
3      companies               9           0
4      documents              52           0
5  profitandloss             231           0
6    prosandcons               6           0

In [14]:
#Save Issues Report
issues_df.to_excel(
    "../reports/data_issues.xlsx",
    index=False
)

print("Data issues report saved")

Data issues report saved