In [6]:
# Load dataset
import pandas as pd
import sqlite3

In [7]:
df = pd.read_excel("../reports/final_business_dataset.xlsx")
print(df.shape)
df.head()

(1383, 34)

,id_x,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,...,other_asset,total_assets,id,operating_activity,investing_activity,financing_activity,net_cash_flow,net_profit_margin,debt_equity,free_cash_flow
0,61,ABB,Dec 2012,1653,1451,202.0,12.0,33,0,19,...,798.0,907.0,61.0,101.0,-59.0,-42.0,1.0,8.771930,0.0,42.0
1,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,...,1040.0,1139.0,62.0,155.0,-144.0,-42.0,-31.0,8.699473,0.0,11.0
2,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,...,1040.0,1139.0,73.0,0.0,0.0,0.0,0.0,8.699473,0.0,0.0
3,63,ABB,Mar 2015,2289,1977,312.0,14.0,48,0,15,...,1274.0,1374.0,63.0,215.0,-187.0,-58.0,-30.0,10.004369,0.0,28.0
4,63,ABB,Mar 2015,2289,1977,312.0,14.0,48,0,15,...,1274.0,1374.0,74.0,-35.0,-1864.0,1902.0,3.0,10.004369,0.0,-1899.0

In [8]:
conn = sqlite3.connect("financial.db")

df.to_sql(
    "financial_data",
    conn,
    if_exists="replace",
    index=False
)

print("Table created successfully")

Table created successfully

In [9]:
#Total Sales
query = """
SELECT SUM(sales) AS total_sales
FROM financial_data
"""
pd.read_sql(query, conn)

   total_sales
0     86493516

In [10]:
#Total Profit
query = """
SELECT SUM(net_profit) AS total_profit
FROM financial_data
"""

pd.read_sql(query, conn)

   total_profit
0       7605085

In [11]:
#Total Assets
query = """
SELECT SUM(total_assets) AS total_assets
FROM financial_data
"""

pd.read_sql(query, conn)

   total_assets
0   208052351.0

In [12]:
#Total Borrowings
query = """
SELECT SUM(borrowings) AS total_borrowings
FROM financial_data
"""

pd.read_sql(query, conn)

   total_borrowings
0       107988326.0

In [13]:
#Top 10 Companies by Profit
query = """
SELECT company_id,
       SUM(net_profit) AS total_profit
FROM financial_data
GROUP BY company_id
ORDER BY total_profit DESC
LIMIT 10
"""

pd.read_sql(query, conn)

  company_id  total_profit
0   RELIANCE        597198
1        TCS        402471
2       ONGC        384948
3   HDFCBANK        376586
4       SBIN        347683
5  ICICIBANK        263890
6  POWERGRID        248646
7  COALINDIA        244466
8       INFY        227989
9        IOC        199551

In [14]:
#Top 10 Companies by Sales
query = """
SELECT company_id,
       SUM(sales) AS total_sales
FROM financial_data
GROUP BY company_id
ORDER BY total_sales DESC
LIMIT 10
"""

pd.read_sql(query, conn)

   company_id  total_sales
0    RELIANCE      7212481
1         IOC      6867333
2        LICI      5140771
3        ONGC      4722104
4        BPCL      3900792
5         PNB      3843516
6  TATAMOTORS      3834286
7        SBIN      3595983
8   TATASTEEL      2151618
9         TCS      1966938

In [15]:
#Top 10 Companies by Assets
query = """
SELECT company_id,
       MAX(total_assets) AS assets
FROM financial_data
GROUP BY company_id
ORDER BY assets DESC
LIMIT 10
"""

pd.read_sql(query, conn)

   company_id     assets
0        LICI  5316047.0
1    HDFCBANK  4030194.0
2   ICICIBANK  2364063.0
3    RELIANCE  1755048.0
4  BANKBARODA  1654775.0
5       CANBK  1535018.0
6    AXISBANK  1518239.0
7   UNIONBANK  1401996.0
8         PFC  1038877.0
9   KOTAKBANK   767667.0

In [16]:
#Highest Borrowings
query = """
SELECT company_id,
       MAX(borrowings) AS borrowings
FROM financial_data
GROUP BY company_id
ORDER BY borrowings DESC
LIMIT 10
"""

pd.read_sql(query, conn)

   company_id  borrowings
0    HDFCBANK   3107503.0
1   ICICIBANK   1651008.0
2  BANKBARODA   1453761.0
3       CANBK   1369780.0
4    AXISBANK   1295302.0
5   UNIONBANK   1251568.0
6         PFC    861961.0
7   KOTAKBANK    520374.0
8    RELIANCE    458991.0
9      RECLTD    445568.0

In [17]:
#Average Debt Equity Ratio
query = """
SELECT AVG(debt_equity) AS avg_debt_equity
FROM financial_data
"""

pd.read_sql(query, conn)

   avg_debt_equity
0         2.816133

In [18]:
#Average Profit Margin
query = """
SELECT AVG(net_profit_margin) AS avg_profit_margin
FROM financial_data
"""

pd.read_sql(query, conn)

   avg_profit_margin
0           17.89178

In [19]:
#Top 10 Companies by Free Cash Flow
query = """
SELECT company_id,
       SUM(free_cash_flow) AS free_cash_flow
FROM financial_data
GROUP BY company_id
ORDER BY free_cash_flow DESC
LIMIT 10
"""

pd.read_sql(query, conn)

  company_id  free_cash_flow
0        TCS        313610.0
1       LICI        277183.0
2        PNB        234650.0
3       VEDL        223145.0
4       SBIN        190012.0
5  POWERGRID        173624.0
6  COALINDIA        163771.0
7       INFY        150471.0
8       ONGC        132465.0
9        IOC        116706.0

In [20]:
#Year-wise Sales Trend
query = """
SELECT year,
       SUM(sales) AS total_sales
FROM financial_data
GROUP BY year
ORDER BY year
"""

pd.read_sql(query, conn)

           year  total_sales
0      Dec 2012        28251
1      Dec 2013        35944
2      Dec 2014        31050
3      Dec 2015        21006
4      Dec 2016        33096
5      Dec 2017        37623
6      Dec 2018        42438
7      Dec 2019        46603
8      Dec 2020        44316
9      Dec 2021        52529
10     Dec 2022        30070
11     Dec 2023        35169
12     Jun 2013        30999
13     Jun 2014        37859
14     Jun 2015        42960
15     Mar 2011         2173
16     Mar 2012         2954
17     Mar 2013      3584364
18     Mar 2014      4093142
19     Mar 2015      4260280
20     Mar 2016      4016124
21  Mar 2016 9m        36650
22     Mar 2017      4478458
23     Mar 2018      5010591
24     Mar 2019      6554797
25     Mar 2020      6610287
26     Mar 2021      6670773
27     Mar 2022      8247186
28     Mar 2023     10079995
29  Mar 2023 15        38937
30     Mar 2024     11107894
31     Sep 2011        11955
32     Sep 2014        10678
33     Sep 2015        10563
34     Sep 2016        10837
35     Sep 2017        11065
36     Sep 2018        12795
37     Sep 2019        13084
38     Sep 2020         9946
39     Sep 2021        13198
40     Sep 2022        16138
41     Sep 2023        19554
42     Sep 2024        22240
43          TTM     10986945

In [21]:
#Year-wise Profit Trend
query = """
SELECT year,
       SUM(net_profit) AS total_profit
FROM financial_data
GROUP BY year
ORDER BY year
"""

pd.read_sql(query, conn)

           year  total_profit
0      Dec 2012          2895
1      Dec 2013          3765
2      Dec 2014          3354
3      Dec 2015          1484
4      Dec 2016          2483
5      Dec 2017          3384
6      Dec 2018          4880
7      Dec 2019          5223
8      Dec 2020          5546
9      Dec 2021          6575
10     Dec 2022          3941
11     Dec 2023          5101
12     Jun 2013          5044
13     Jun 2014          7315
14     Jun 2015          7768
15     Mar 2011           264
16     Mar 2012           381
17     Mar 2013        307038
18     Mar 2014        346246
19     Mar 2015        322314
20     Mar 2016        295798
21  Mar 2016 9m          6745
22     Mar 2017        385044
23     Mar 2018        362271
24     Mar 2019        395613
25     Mar 2020        383382
26     Mar 2021        563281
27     Mar 2022        850739
28     Mar 2023        908094
29  Mar 2023 15          3024
30     Mar 2024       1221028
31     Sep 2011           868
32     Sep 2014           603
33     Sep 2015          1174
34     Sep 2016          2914
35     Sep 2017          1137
36     Sep 2018           901
37     Sep 2019          1099
38     Sep 2020           769
39     Sep 2021          1089
40     Sep 2022          1543
41     Sep 2023          1962
42     Sep 2024          2718
43          TTM       1168288

In [22]:
#Companies with Positive Free Cash Flow
query = """
SELECT company_id,
       COUNT(*) AS records
FROM financial_data
WHERE free_cash_flow > 0
GROUP BY company_id
ORDER BY records DESC
"""

pd.read_sql(query, conn)

    company_id  records
0          PNB       35
1        TECHM       24
2   ASIANPAINT       24
3   BAJAJ-AUTO       22
4          ABB       15
..         ...      ...
91      RECLTD        1
92         M&M        1
93        IRFC        1
94  BAJAJFINSV        1
95  ADANIGREEN        1

[96 rows x 2 columns]

In [24]:
#Close Connection
conn.close()
print("Database connection closed")

Database connection closed